# Generated by Django 2.2.2 on 2019-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Travel', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='category',
            field=models.ManyToManyField(to='elearning.Category'),
        ),
    ]
