# Generated by Django 2.2.2 on 2019-06-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_auto_20190629_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='name',
        ),
        migrations.AddField(
            model_name='exams',
            name='category',
            field=models.ManyToManyField(to='elearning.Category'),
        ),
    ]
