# Generated by Django 2.2.2 on 2019-06-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_auto_20190629_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='image',
            new_name='cover',
        ),
    ]
