# Generated by Django 2.2.2 on 2019-06-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_auto_20190629_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='cover',
            new_name='image',
        ),
    ]
