# Generated by Django 2.2.2 on 2019-07-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_auto_20190701_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='image',
            field=models.FileField(upload_to='elearning/'),
        ),
    ]
