# Generated by Django 2.2.2 on 2019-07-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_auto_20190701_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='image',
            new_name='image_url',
        ),
    ]
