# Generated by Django 2.2.2 on 2019-07-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_auto_20190707_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='image_url',
            field=models.CharField(default='', max_length=220),
        ),
    ]
