# Generated by Django 2.2.2 on 2019-07-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0011_auto_20190707_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='image_url',
        ),
        migrations.AddField(
            model_name='exams',
            name='images',
            field=models.ImageField(null=True, upload_to='elearning'),
        ),
    ]
